language: java

jdk:
- openjdk11

addons:
  firefox: latest
  sonarcloud:
    organization: "gaia-app"

env:
  global:
    - MOZ_HEADLESS=1

cache:
  directories:
    - $HOME/.m2

git:
  depth: false

stages:
  - name: test
  - name: deploy
    if: branch = master AND tag IS present

before_script:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - tar -xzf geckodriver-v0.26.0-linux64.tar.gz
  - sudo cp geckodriver /usr/bin

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script:
      # fetching master refs when building other branches helps sonar computing PRs
      - git fetch origin +refs/heads/master:refs/remotes/origin/master
      # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
      - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify org.jacoco:jacoco-maven-plugin:report sonar:sonar
#    - stage: test
#      name: "Visual Non Regression Tests"
#      if: env(PERCY_TOKEN) AND ( type = pull_request OR branch = master )
#      script:
#      - npm install @percy/agent
#      - npx percy exec -- mvn test -Dgroups=e2e
    - stage: deploy
      name: "Deploy to hub.docker.com"
      script:
      - export DOCKER_TAG=`echo $TRAVIS_TAG | cut -d 'v' -f 2`
      - echo "$DOCKER_PASSWORD" | docker login -u codekaio --password-stdin
      - docker build -t codekaio/gaia:$DOCKER_TAG .
      - docker push codekaio/gaia:$DOCKER_TAG

after_success:
  - wget https://raw.githubusercontent.com/CodeKaio/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/CodeKaio/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
